---
all:
  hosts:
    lab.bk.local:
      ansible_host: 172.24.128.5
    workstation.bk.lab:
      ansible_host: 172.24.128.6
    satellite.bk.lab:
      ansible_host: 172.24.128.7
    idm01.bk.lab:
      ansible_host: 172.24.128.8
    idm02.bk.lab:
      ansible_host: 172.24.128.9
  children:
    labhost:
      hosts:
        lab.bk.local:
    workstation:
      hosts:
        workstation.bk.lab:
    satellite:
      hosts:
        satellite.bk.lab:
    idmserver:
      hosts:
        idm01.bk.lab:
    idmreplicas:
      hosts:
        idm02.bk.lab:
