---
- name: Delete a host from Ansible Automation Platform
  hosts: all
  become: false
  gather_facts: false

  vars:
    aap_username: "{{ vault_aap_username | default(lookup('env', 'CONTROLLER_USERNAME')) }}"
    aap_password: "{{ vault_aap_password | default(lookup('env', 'CONTROLLER_PASSWORD')) }}"
    aap_hostname: "{{ vault_aap_hostname | default(lookup('env', 'CONTROLLER_HOST')) }}"
    aap_validate_certs: "{{ vault_aap_validate_certs | default(lookup('env', 'CONTROLLER_VERIFY_SSL')) }}"
    controller_validate_certs: "{{ aap_validate_certs }}"

  pre_tasks:
    - name: Set up Authentication
      block:
        - name: Get token for future requests
          ansible.builtin.uri:
            url: https://{{ aap_hostname }}/api/gateway/v1/tokens/
            user: "{{ aap_username }}"
            password: "{{ aap_password }}"
            method: POST
            force_basic_auth: true
            validate_certs: false
            status_code: 201
          register: authtoken_res

        - name: Set the oauth token to be used
          ansible.builtin.set_fact:
            aap_oauthtoken: "{{ authtoken_res.json.token }}"
            controller_oauthtoken: "{{ authtoken_res.json.token }}"
            aap_oauthtoken_url: "{{ authtoken_res.json.url }}"
            controller_oauthtoken_url: "{{ authtoken_res.json.url }}"
      no_log: "{{ controller_configuration_filetree_create_secure_logging | default('false') }}"
      when: aap_oauthtoken is not defined

  tasks:
    - name: Set the hm_id fact
      ansible.builtin.set_fact:
        hm_id: "{{ query('ansible.controller.controller_api', 'host_metrics', query_params={ 'hostname': vm_name }) | map(attribute='id') | join }}"

    - name: Delete host from host metrics via URI
      ansible.builtin.uri:
        url: https://{{ aap_hostname}}/api/controller/v2/host_metrics/{{ hm_id }}/
        method: DELETE
        validate_certs: false
        headers:
          Content-Type: application/json
          Authorization: Bearer {{ aap_oauthtoken }}
        status_code:
          - 200
          - 204
      register: delete_result
      changed_when: '"OK" in delete_result.msg'

  post_tasks:
    - name: Delete the Authentication Token used
      ansible.builtin.uri:
        url: https://{{ aap_hostname }}{{ aap_oauthtoken_url }}
        user: "{{ aap_username }}"
        password: "{{ aap_password }}"
        method: DELETE
        force_basic_auth: true
        validate_certs: "{{ aap_validate_certs }}"
        status_code: 204
