---
- name: Create an Organization in AAP
  hosts: all
  become: false
  gather_facts: false

  vars:
    aap_username: "{{ vault_aap_username | default(lookup('env', 'CONTROLLER_USERNAME')) }}"
    aap_password: "{{ vault_aap_password | default(lookup('env', 'CONTROLLER_PASSWORD')) }}"
    aap_hostname: "{{ vault_aap_hostname | default(lookup('env', 'CONTROLLER_HOST')) }}"
    aap_validate_certs: "{{ vault_aap_validate_certs | default(lookup('env', 'CONTROLLER_VERIFY_SSL')) }}"
    controller_validate_certs: "{{ aap_validate_certs }}"

  pre_tasks:
    - name: Set up Authentication
      block:
        - name: Get token for future requests
          ansible.builtin.uri:
            url: https://{{ aap_hostname }}/api/gateway/v1/tokens/
            user: "{{ aap_username }}"
            password: "{{ aap_password }}"
            method: POST
            force_basic_auth: true
            validate_certs: false
            status_code: 201
          register: authtoken_res

        - name: Set the oauth token to be used
          ansible.builtin.set_fact:
            aap_oauthtoken: "{{ authtoken_res.json.token }}"
            controller_oauthtoken: "{{ authtoken_res.json.token }}"
            aap_oauthtoken_url: "{{ authtoken_res.json.url }}"
            controller_oauthtoken_url: "{{ authtoken_res.json.url }}"
      no_log: "{{ controller_configuration_filetree_create_secure_logging | default('false') }}"
      when: aap_oauthtoken is not defined

  tasks:
    - name: Create the Organization
      ansible.platform.organization:
        gateway_hostname: "{{ aap_hostname }}"
        gateway_username: "{{ aap_username }}"
        gateway_token: "{{ aap_oauthtoken }}"
        name: "{{ org_name }}"
        state: present

  post_tasks:
    - name: Delete the Authentication Token used
      ansible.builtin.uri:
        url: https://{{ aap_hostname }}{{ aap_oauthtoken_url }}
        user: "{{ aap_username }}"
        password: "{{ aap_password }}"
        method: DELETE
        force_basic_auth: true
        validate_certs: "{{ aap_validate_certs }}"
        status_code: 204
      when: aap_oauthtoken_url is defined