---
- name: Synchronize Automation Hub Collection Repositories
  hosts: all
  become: false
  tasks:
    - name: Synchronize the Repositories
      ansible.hub.collection_repository_sync:
        name: "{{ item }}"
      loop: "{{ repository_name }}"
